//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContacts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int ID { get; set; }
        public int MountID { get; set; }
        public int EzafehKar { get; set; }
        public int WorkDay { get; set; }
        public int ActiveWorkDay { get; set; }
        public double GiftSalary { get; set; }
        public double RewardSalary { get; set; }
        public double Porsant { get; set; }
        public int RestTime { get; set; }
        public int RestDay { get; set; }
        public double HelpSalary { get; set; }
        public double PenaltySalary { get; set; }
        public double SaftehPrice { get; set; }
        public double SaftehBedehi { get; set; }
        public double Bedehi { get; set; }
        public double PBon { get; set; }
        public string Description { get; set; }
        public int PersonelID { get; set; }
        public int BaseSalaryID { get; set; }
    
        public virtual Mounts Mounts { get; set; }
        public virtual Personels Personels { get; set; }
    }
}
