//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContacts
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseSalaries
    {
        public int ID { get; set; }
        public int YearID { get; set; }
        public double BaseSalaryDaily { get; set; }
        public double HomeSalary { get; set; }
        public double NavSalary { get; set; }
        public double BonSalary { get; set; }
        public double EzafehTimeSalary { get; set; }
        public double RestSalary { get; set; }
        public double KasrGheibat { get; set; }
        public string LevelPrice { get; set; }
    }
}
