//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContacts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personels()
        {
            this.Salaries = new HashSet<Salaries>();
        }
    
        public int ID { get; set; }
        public int PID { get; set; }
        public int NID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Mobile { get; set; }
        public string BankID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salaries> Salaries { get; set; }
    }
}
